### ISSUE TITLE
Ver. 0.7.3 does not open on Windows

### ISSUE THREAD

**Issue by Shellfishgene** [David-OConnor/plascad#1]
Hi!

I just tried v0.7.3 but it seems to close before the window appears on Windows 10. When started in a console also it just exits immidiately without error. v0.7.2 works as expected.

Thanks!

**Comment by David-OConnor** [comment]
Thanks for the report! Fixed, and released as 0.7.4.

**Comment by Shellfishgene** [comment]
Thanks!
