### ISSUE TITLE
Unwanted input in the sequence. 

### ISSUE THREAD

**Issue by raghavnagpal** [David-OConnor/plascad#2]
Hey, Thanks for creating this great tool. 
I have observed few issues with the tool, 

1. in the sequence view when I am trying to add a primer while naming the primer the input is also getting added to the sequence, can you add a feature where we can freeze the sequence to read only mode etc...
2. I do not find an option to mark a primer sequence as reverse.
3. Some times the text (sequence) displayed do not wrap around. During adding primers.

**Comment by David-OConnor** [comment]
Great finds! Would love to fix them for the next release. I believe 1. should already be fixed in the Git version.

**Comment by David-OConnor** [comment]
*Some of the accidental input is already fixed, but I agree that we need a freeze/lock.

**Comment by David-OConnor** [comment]
Lock is on Git now.

Could you please clarify on #2? Of note, the primers can match either direction, in the current version.

**Comment by David-OConnor** [comment]
Could you please clarify on 3? For example, I tried adding a primer from the end, to the start, and it seemed to work.

**Comment by David-OConnor** [comment]
Closing, pending clarification.
